// src/routes/news.rs

use axum::{extract::State, Json};
use chrono::Utc;
use tracing::info;

use crate::news::client::{NewsFetchRequest, NewsFetchResponse};
use crate::news::models::NewsItem;
use crate::AppState;

/// Mock /news/fetch handler.
///
/// DEV-ONLY stub:
/// - Does NOT call real search/LLM.
/// - Returns 1–2 fake news items based on company name + domain.
///
/// Request:  NewsFetchRequest
/// Response: NewsFetchResponse { company_id, news_items: Vec<NewsItem> }
pub async fn mock_fetch_news_handler(
    State(_state): State<AppState>, // reserved for future DB/LLM usage
    Json(req): Json<NewsFetchRequest>,
) -> Json<NewsFetchResponse> {
    info!(
        "mock_fetch_news_handler: client_id={} company_id={} name={} domain={}",
        req.client_id, req.company_id, req.company_name, req.domain
    );

    let now = Utc::now();

    // Normalize domain into a fake base URL
    let domain_clean = req
        .domain
        .trim_start_matches("http://")
        .trim_start_matches("https://")
        .trim_end_matches('/');

    let base_url = format!("https://{}/", domain_clean);

    // 1st fake news item
    let item1 = NewsItem {
        company_id: req.company_id,
        title: format!("{} announces major growth initiative", req.company_name),
        date: Some(now),
        location: None,
        summary: Some(format!(
            "Mock summary: {} is investing in outbound and sales growth (generated by mock service).",
            req.company_name
        )),
        url: format!("{}mock-news-1", base_url),
        source_type: "mock".to_string(),
        source_name: Some("mock_service".to_string()),
        tags: vec!["product_launch".to_string(), "growth".to_string()],
        confidence: 0.9,
    };

    // 2nd fake news item
    let item2 = NewsItem {
        company_id: req.company_id,
        title: format!("{} explores new markets", req.company_name),
        date: Some(now),
        location: None,
        summary: Some(format!(
            "Mock summary: {} is expanding into new regions (mock).",
            req.company_name
        )),
        url: format!("{}mock-news-2", base_url),
        source_type: "mock".to_string(),
        source_name: Some("mock_service".to_string()),
        tags: vec!["expansion".to_string(), "mock".to_string()],
        confidence: 0.8,
    };

    let response = NewsFetchResponse {
        company_id: req.company_id,
        news_items: vec![item1, item2],
    };

    Json(response)
}
